spring:
  application:
    name: config-server  cloud:    config:      server:        git:          uri: https://github.com/vatsanTraining/spring-cloud-config          search-paths:          - '{application}'
    
server:  port: 8888
  